name        : improvised
synopsis    : First class typeclass instances
description : See the README file in the project repository
version     : 0.1.0.0
category    : Language
git         : "https://gitlab.com/thematten/first-class-instances"
license     : BSD3
author      : "Sandy Maguire"
maintainer  : "sandy@sandymaguire.me"
copyright   : "2020 Sandy Maguire"

extra-source-files : [README.md, ChangeLog.md]

dependencies :
- base             >=4.7     && <5
- containers       >=0.6.0.1 && <0.7
- template-haskell >=2.13    && <2.16
- transformers     >= 0.5.2.0 && < 0.6
- lens             >= 4.17.1 && < 5
- type-errors      >= 0.2.0.0 && < 0.3

library :
  source-dirs : src
  other-modules:
    - FCI.Internal
    - FCI.Internal.TH
    - FCI.Internal.Types
    - Test.Improvised.Internal
    - Test.Improvised.TH
    - Test.Improvised.THStuff

tests :
  first-class-instances-test :
    main         : Main.hs
    source-dirs  : test
    ghc-options  :
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies :
    - improvised
    - hspec
    build-tools:
    - hspec-discover >= 2.0

ghc-options :
- -ferror-spans
- -Wall
# - -Werror
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Widentities
- -Wredundant-constraints
- -Wpartial-fields
- -Wcompat

default-extensions :
- ConstraintKinds
- DataKinds
- DuplicateRecordFields
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

